### ISSUE TITLE
Forced update

### ISSUE THREAD

**Issue by pizsos** [new-xkit/XKit#1748] opened 2019-11-21 19:38 UTC
Xkit is trying to force update extensions but they aren't working bc i cannot reach the server. I've tried to let it load but nothings happening and i cannot use tumblr at all in this state. Is there a way to do updates manually?

**Comment by AprilSylph** [comment] 2019-11-21 19:42
duplicate of/answered in #1746

**Closed by AprilSylph** 2019-11-21 19:42 UTC
