### ISSUE TITLE
Editing reblogged posts with Editable Reblogs enabled causes doubled original post

### ISSUE THREAD

**Issue by rimbaum** [new-xkit/XKit#344] opened 2015-08-25 01:23 UTC
Not sure how else to explain it, but if you check out this post I made, you'll see what I mean.

![screenshot-3](https://cloud.githubusercontent.com/assets/4296434/9456429/707273f0-4aa5-11e5-947f-4ed9a257e3d0.png)

extension info: https://gist.github.com/0482fe53153b49122189
Linux Mint 17.2, Chrome 44

**Comment by ThePsionic** [comment] 2015-08-25 10:30
Dupe of #100

**Closed by ThePsionic** 2015-08-25 10:30 UTC
