### ISSUE TITLE
Open In Tabs still bugged

### ISSUE THREAD

**Issue by schaufel4** [new-xkit/XKit#80] opened 2015-08-01 01:19 UTC
Open In Tabs opens links and blogs in tabs, but nothing on the sidebar (tracked tags, likes, following/ers, etc.). Also, if you enable opening blogs in new tabs, it forces photosets to open in new tabs as well, which makes photosets extremely annoying to view since you can't click through them on the dash anymore.

**Comment by dlmarquis** [comment] 2015-08-01 02:09
@schaufel4 what browser and OS do you have? I'm on Ubuntu 14.04 and Firefox 39 and have the sidebar issue but not the photoset issue.

**Comment by schaufel4** [comment] 2015-08-01 02:16
Firefox 39 on Windows 7 Pro. The photoset issue only happens when I've toggled the "Open in new tab instead of blog sidebar" option.

**Comment by schaufel4** [comment] 2015-08-10 04:05
This is still bugged.

**Comment by Wolvan** [comment] 2015-08-10 06:35
@schaufel4 Chrome 44 on Windows 7 Pro x64 here, can't reproduce the problem

**Comment by schaufel4** [comment] 2015-08-15 16:06
Still nothing on the sidebar will open in a new tab as of 1.1.6. It DID partially fix the photoset issue when "Open in new tab instead of sidebar" is toggled - photosets with multiple photos now open properly on the dash as they should, but a single picture is still forced into a new tab.

**Comment by blackjackkent** [comment] 2015-08-27 18:09
Resolved by #268

**Closed by blackjackkent** 2015-08-27 18:09 UTC
Labels: E-Open In Tabs
