### ISSUE TITLE
Editable Reblogs/a few other extensions including outbox won`t play nice with multifox

### ISSUE THREAD

**Issue by wukongandsun** [new-xkit/XKit#111] opened 2015-08-02 18:42 UTC
much like a similar post previously, I am having issues with the multifox and xkit meshing. But it outright won`t allow any of the blogs on my multifox use editable reblogs. I`ve tried it on several now, and it just hates this I suppose.

**Comment by nightpool** [comment] 2015-08-06 22:49
closing as this is most likely a multifox issue.

**Comment by nightpool** [comment] 2015-08-06 22:50
(also even if it isn't its a dupe of #108)

**Closed by nightpool** 2015-08-06 22:49 UTC
