### ISSUE TITLE
Remove third party warning for new-xkit and move all of our new extensions to new-xkit

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#276] opened 2015-08-14 06:23 UTC
Third party is rapidly beginning to lose its meaning. I want to be able to actually say that we aren't going to touch third party things because incorporating existing community code like #226 would be really cool even though that's 3kloc of sparsely-documented JavaScript.

**Comment by nightpool** [comment] 2015-08-14 15:08
+1

we should also just rename all of the studioxenix extensions to new-xkit, because we're maintaining them going forward

**Comment by Wolvan** [comment] 2015-08-14 15:11
They were still created by xenix though and most of his code is still made by him.
On the other hand it would lead people to new-xkit's github instead of his

**Comment by nightpool** [comment] 2015-08-14 15:23
dupe of #126 but I'm going to close that one instead because we got sidetracked talking about gitter

**Comment by 0xazure** [comment] 2015-11-08 19:59
What if we renamed the current "DEVELOPER" field to something more along the lines of "AUTHOR" or "CREDITS", made it an optional field (if it isn't already) for extensions, and completely remove the code that pops up a warning if the `DEVELOPER` is not on the "approved" list?  I definitely agree that "Third Party" doesn't mean anything anymore.  If it's on the extension gallery, we officially support it as the core team, and since XKit Packs [have been depreciated](https://github.com/new-xkit/XKit/pull/488), there's no way for third-party code to get into XKit outside of the editor.

**Comment by nightpool** [comment] 2015-11-08 20:54
we need the third party warning, but it shouldn't apply to any extensions
that are in the gallery. I think we should replace the about+support page
with a "credits" page that credits all the individual extension authors.

**Comment by 0xazure** [comment] 2015-11-08 22:29
Why do we need the third-party warning?  Specifically for code added through the editor?  Because it's rather straight-forward to spoof that, if it's a third-party extension that people are being told to copy/paste in and they have no extensive technical chops.

My initial reaction is that I'm not a fan of divorcing the credits from the extensions and putting them in a separate page.  Having that information on the "detail" view of the extension is where it should be, imo.  However, for extensions that have significantly evolved and been re-written by the core team, having the "originating" author's information there doesn't make sense.  In those cases, giving credit for the initial version(s) of the extension(s) on a "credits" page/section like has been done for the inclusion of `moment.js` and `tiptip.js` wouldn't go amiss.

**Comment by 0xazure** [comment] 2015-11-08 22:37
Regardless, we would need a better mechanism for identifying "third-party" user-added (through the editor, presumably) extensions than checking the `DEVELOPER` against a whitelist.  Checking `NAME` against the `gallery.json` might be a better idea, since `NAME` should be unique(ish).  We could look into checksumming the extension contents, too, in order to pick out modified extension scripts from the `gallery.json`, but that might be a little overkill.

**Comment by Wolvan** [comment] 2015-11-08 22:44
I'd personally say we just check if an extension is part of the gallery.json, no need to go overkill with checksums (since that would probably also include having to make checksums for each version of the extensions

**Comment by Dhwty** [comment] 2017-07-02 20:19
Extensions developed by new-xkit are no longer showing the 'third party extension' warning. Just checked several, but can't figure out which PR fixed this.

**Comment by nightpool** [comment] 2017-07-02 20:27
@Dhwty thanks for going through these old issues and checking them!

**Comment by nightpool** [comment] 2017-07-02 20:33
this was fixed by #322 but I'm reopening this because there are still unresolved concerns about how to properly credit creators of extensions while also taking responsibility for bugs into the new-xkit team.

**Closed** 2020-04-29 08:55 UTC
Labels: enhancement
