### ISSUE TITLE
Inaccurate Timestamps

### ISSUE THREAD

**Issue by contentmint** [new-xkit/XKit#698] opened 2015-10-31 07:58 UTC
I received a message just now, but the absolute time stamp is six hours behind the actual. The relative time also indicates 6 hours ago. I know tumblr is based in New York, so my guess is that this has to do with the time zone difference?

**Comment by ThePsionic** [comment] 2015-10-31 09:11
Duplicate of #116.

**Closed by ThePsionic** 2015-10-31 09:11 UTC

**Comment by nightpool** [comment] 2015-10-31 15:56
Yeah this is a long standing issue. We assumed that tumblr was serving
timestamps relative to utc-5, but instead they're served in whichever
timezone you have set on your blog settings, but without any timezone
information.
