### ISSUE TITLE
one click reblog wont work on mozilla

### ISSUE THREAD

**Issue by violetta-ee** [new-xkit/XKit#1565] opened 2018-06-02 21:18 UTC
once again the one click reblog doesnt work at all. you keep getting the xkit error code.

**Comment by Codex-** [comment] 2018-06-04 03:50
Same here, works correctly on chrome.
![image](https://user-images.githubusercontent.com/8297838/40897243-108ba478-680e-11e8-89a2-9f7c799948d3.png)
Would also be handy if the exception view allowed you to copy the error code into some predefined format for logging issues etc.

I found that it is the Ghostery add on in firefox specifically that causes this to fail, can reproduce by installing ghostery and blocking all.

To allow this to work again normally you need to disable enhanced anti tracking:
![image](https://user-images.githubusercontent.com/8297838/40897376-d9c944c6-680e-11e8-82eb-bfaa92e2cdaa.png)

However this works correctly in chrome, not sure if this lays with how xkit works on chrome vs firefox or if this is with ghostery behaviour.

**Comment by violetta-ee** [comment] 2018-06-04 17:30
I don't use ghostery at all though, I dont have this add on installed so I don't think that's what's causing one click postage to fail. At least not on my part. But it is true I am getting the same error pop up when using one click postage as well.

**Comment by AprilSylph** [comment] 2018-06-05 00:20
@violetta-ee what other add-ons _do_ you have installed? without knowing, they cannot be eliminated as conflicts.

**Comment by AprilSylph** [comment] 2019-01-12 07:54
hopefully resolved by #1536 - other addons can no longer block the kitty request without breaking vanilla tumblr too since we now inject it

**Closed by AprilSylph** 2019-01-12 07:54 UTC
Labels: E-One-Click Postage, unconfirmed
