### ISSUE TITLE
Add "unfollow" button to inactivity finder

### ISSUE THREAD

**Issue by piedoom** [new-xkit/XKit#918] opened 2016-01-17 18:54 UTC
The inactivity finder extension is great, but as it stands now, it seems that one must click each individual blog to unfollow inactive users.  A helpful feature would be to include an "unfollow" button next to the user's name, or an "unfollow all" button.

**Comment by Wolvan** [comment] 2016-01-17 18:57
Duplicate of #189, Fixed by #696

**Closed by Wolvan** 2016-01-17 18:57 UTC
