### ISSUE TITLE
Searching with Blacklist breaks list view

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#726] opened 2015-11-06 11:11 UTC
When searching for a tag in list view and there are blacklisted posts in the results, the page does not load more posts after the first batch. This is resolved when you unhide all blacklisted posts.

To reproduce:
- Add blacklisted words (the reporter in Gitter had "wwe", "wrestling" blacklisted)
- Search for a tag (reporter was searching "undertaker") **Note:** /search/tag, not /tagged/tag
- Go into list view (![list view icon](http://i.imgur.com/UangBNM.png))
- Scroll down and observe that only a few posts are loaded
- Unhide the blacklisted posts, scroll down again and observe that more posts are loaded

Tested on both Firefox and Chrome.

**Comment by nightpool** [comment] 2017-05-29 18:42
dupe of #889

**Closed by nightpool** 2017-05-29 18:42 UTC
Labels: bug, E-Blacklist
