### ISSUE TITLE
Satsukimous cannot be installed from the gallery

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#272] opened 2015-08-14 03:42 UTC
![satsuki-noooo](https://cloud.githubusercontent.com/assets/1041456/9266879/fbff4752-4214-11e5-88b0-4d5ce2dcbb81.PNG)

**Comment by bvtsang** [comment] 2015-08-14 04:02
In `Extensions/dist` on the `gh-pages` branch, I don't see satsukimous.json. Could this be a reason for this error?

**Comment by finagle29** [comment] 2015-08-14 04:09
@bvstang i think so, but I'm not 100% sure why because @hobinjk rebuilt gh-pages after #269

**Comment by hobinjk** [comment] 2015-08-14 04:14
It exists locally, I'm investigating now

**Comment by hobinjk** [comment] 2015-08-14 04:16
Oh wow, really sneaky bug caused by 3bdff43ee5af51c6386c94e4e28be9d4d31572c5

**Comment by hobinjk** [comment] 2015-08-14 04:17
Should be fixed now

**Closed by hobinjk** 2015-08-14 04:17 UTC
Labels: bug, E-Satsukimous
