### ISSUE TITLE
One-Click Reply needs to be brought up to speed with new blockquote behavior

### ISSUE THREAD

**Issue by blackjackkent** [new-xkit/XKit#432] opened 2015-09-03 19:22 UTC
Oneclick reply formats replies with a blockquote in the middle:

so and so replied to your post:

> here's the reply

This will not work with the new blockquote parsing paradigm and will look funny for anyone viewing things with the new reblog design.

**Comment by dlmarquis** [comment] 2015-09-25 01:22
Okay, I think this and #454 are dupes of eachother. I left a note there about display weirdness I was experiencing. How are blockquotes parsed now that OCR breaks? Since I'm assuming blockquotes still work in general.

**Comment by nightpool** [comment] 2015-09-25 03:12
yep cosign dupe of #454

**Comment by AprilSylph** [comment] 2019-01-04 10:58
dupe of closed issue

**Closed by AprilSylph** 2019-01-04 10:58 UTC
Labels: E-One-Click Reply, bug
