### ISSUE TITLE
'No Recommended' causes dashboard to keep loading

### ISSUE THREAD

**Issue by ecrthling** [new-xkit/XKit#1890] opened 2020-07-04 19:59 UTC
My dashboard was stuck on "loading" and I couldn't figure out why. I messaged support and then just went to my extensions and kept disabling each extension to see if any was causing the issue. 

It turns out the 'No Recommended' takes out the recommended posts but won't allow my dashboard to load (on more than one account) and sometimes when it does, it shows the first few posts and then the loading thing again.

![issue](https://user-images.githubusercontent.com/67841437/86520149-4055ce80-be39-11ea-93aa-e21ece404ccd.png)
![issue1](https://user-images.githubusercontent.com/67841437/86520151-42b82880-be39-11ea-9772-2e5bf028a0b8.png)

Thank you for your time!

**Comment by AprilSylph** [comment] 2020-07-06 08:38
unable to reproduce with No Recommended 2.3.2 on Firefox 68.10.0esr

**Comment by spirated** [comment] 2020-07-08 21:34
I have had this same issue on all of my blogs. The continuous loading happens on blogs where endless scroll is selected. On blogs where endless scroll is deselected, the dashboard simply shows up as a blank page with a next button. For reference, I am using Chrome Version 83.0.4103.116
![j](https://user-images.githubusercontent.com/68033831/86972567-2c63e280-c141-11ea-9edc-aaaa89a7d87b.png)
![j1](https://user-images.githubusercontent.com/68033831/86972584-2ff76980-c141-11ea-8147-0e894c73c59a.png)

**Comment by AprilSylph** [comment] 2020-08-07 21:04
this should be fixed by #1909, which makes the underlying tumblr issue of "my dashboard consists entirely of recommended posts" more apparent

**Closed by AprilSylph** 2020-08-07 21:04 UTC
Labels: E-No Recommended, unconfirmed
