### ISSUE TITLE
Relative Time bug in Alternative Timestamps

### ISSUE THREAD

**Issue by realityfabric** [new-xkit/XKit#498] opened 2015-09-15 11:13 UTC
Possibly the same bug as in https://github.com/new-xkit/XKit/issues/116

My computer system time is set to Pacific Time (-7:00), but I have my blog set to Islamabad (+5:00) for irrelevant reasons
When my blog is set to:
-7:00:      2015-09-15 03:55 :: 15 minutes ago
+5:00:     2015-09-15 15:55 :: in 12 hours
+4:00:     2015-09-15 14:55 :: in 11 hours

This leads me to believe that the timestamp itself is based on the blog timezone, while the relative timestamp is based on system time.

I don't know for sure, but I usually use the relative timestamp more than the regular timestamp

**Comment by ThePsionic** [comment] 2015-09-15 12:54
I have a feeling that https://github.com/new-xkit/XKit/blob/master/Extensions/timestamps.js#L262 and https://github.com/new-xkit/XKit/blob/master/Extensions/timestamps.js#L322 don't work nicely together, creating this issue. Needs further investigation.

**Comment by nightpool** [comment] 2015-09-15 14:27
yeah this is def a dupe of #116, thanks. We initially assumed that tumblr would always serve EST timezones, but it turns out that tumblr serves times based on the blog timezone, but without timezone information alol.

**Closed by nightpool** 2015-09-15 14:27 UTC
Labels: E-Timestamps, waffle:bug
