### ISSUE TITLE
Post Limit Checker failing for some unknown subset of users

### ISSUE THREAD

**Issue by allybees** [new-xkit/XKit#1071] opened 2016-06-15 08:50 UTC
it opens goes to loading screen and the nothing happens...

**Comment by ThePsionic** [comment] 2016-06-15 11:41
![limit](https://cloud.githubusercontent.com/assets/842080/16078345/bbc308c8-32fe-11e6-81d3-224aabaaf2bd.PNG)
It takes a little while (2-10 minutes) and the loading bar resets a few times during the process. Could you try it again and see if it still doesn't work?

**Comment by allybees** [comment] 2016-06-15 11:48
yeah ive been trying for 2 days now.. it looks like its loading but nothing happens i left it for half an hour and you just get the gathering info screen.. a lot of ppl have had this happen i thought it was just me but it doesn't seem to be.

Date: Wed, 15 Jun 2016 04:41:30 -0700

**Comment by ThePsionic** [comment] 2016-06-15 13:45
What browser + version are you using, what version is your XKit, what version is your Post Limit Checker?

**Comment by allybees** [comment] 2016-06-15 13:51
chrome and the most up to date version .. I have been using it for months and it was working fine until a couple of days ago.

Date: Wed, 15 Jun 2016 06:45:14 -0700

**Comment by Wolvan** [comment] 2016-06-15 13:53
Checking in with Chrome 51 and current Post Limit Checker to say that it works just fine for me

**Comment by allybees** [comment] 2016-06-15 13:56
well its not for me!! i dont understand.. it was fine then just stopped, I have re installed, everything else works fine but not that..  

Date: Wed, 15 Jun 2016 06:53:34 -0700

**Comment by Wolvan** [comment] 2016-06-15 13:58
What version of chrome ARE you using. Saying latest is not an option

**Comment by allybees** [comment] 2016-06-15 14:14
51.0 and  7.7.1 version of new xkit.. current one on chrome web store

Date: Wed, 15 Jun 2016 06:58:09 -0700

**Comment by nightpool** [comment] 2016-06-15 18:02
Can someone try hiding their main blog and then checking in to see if post checker breaks? I think its probably either if the main blog is hidden or if it can't find *any* blogs to grab info from

**Comment by nightpool** [comment] 2016-06-15 18:23
(@allybees did you mean to close this? as far as I can tell this is still happening to a ton of people)

**Comment by ThePsionic** [comment] 2016-06-15 21:02
I can confirm that toggling off the option "Allow logged-out users to see this blog" breaks the Post Limit Checker. This is because the API returns a 404 error when attempting to request anything from a hidden blog.

**Comment by nightpool** [comment] 2016-06-15 21:42
@ThePsionic what's the behavior? does it sit forever?

This sounds like something we should fix, but I'm still not convinced that's the main issue here. Hidden blogs have been around for a while now and they've always worked the same as far as the API goes

**Comment by ThePsionic** [comment] 2016-06-15 21:52
It sits forever indeed. The loading interface opens, but the loading bar never actually progresses and the user gets no feedback at all that it errors out. The only indication of this is the 404 error in the Javascript console.

**Comment by allybees** [comment] 2016-06-16 06:37
ok thanks..

Date: Wed, 15 Jun 2016 14:52:20 -0700

**Closed** 2020-04-29 08:47 UTC
Labels: E-Post Limit Checker, P-Medium, bug
