### ISSUE TITLE
Editable Reblogs deletes captions

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#375] opened 2015-08-27 20:58 UTC
>With Editable Reblogs enabled, reblogging a Photo post with comments on it deletes the comments automatically 2/5 times. This has been persistent since the extension has been around. Not certain why it is happening. At one point thought it was reblogging a post too fast so the extension wouldn't have time to work, but it has done it at times where I have purposefully waited for the page to fully load and then some.

>Hey, I've been noticing today that every so often when I try to draft a post, the body of the post ends up disappearing. It's happened with photosets (the caption below disappeared) and with text posts (everything other than the title disappeared). It hasn't been consistent so far, but I also noticed that it's more likely if I haven't added anything to the post. I hope this makes sense :P I think it's related to the Editable Reblogs extension.

**Comment by ThePsionic** [comment] 2015-08-27 21:26
From the support Gitter:
><TSFennec> Text keeps disappearing when I queue things
<TSFennec> Like, if pictures have credits/captions, the image reblogs, but not the text.
<TSFennec> Sometimes if I try it again the text will show up in the queued post... Other times even when I do it a few times it's not working.
<TSFennec> (I'm fairly sure this is an issue with the editable reblogs extension. Can't be sure it's not Tumblr itself, but since I haven't heard from others about it...)
<TSFennec> Oddly enough, it only seems to happen when I'm queueing, not when I'm just posting then.

**Comment by nightpool** [comment] 2015-08-27 21:34
This is a dupe of #100

**Comment by nightpool** [comment] 2015-08-27 21:35
we've been tracking both bugs there, IIRC

**Comment by ThePsionic** [comment] 2015-08-27 21:37
Seems quite odd to track both of those bugs under the same title, which is a completely different issue.

**Comment by nightpool** [comment] 2015-08-27 23:43
there might be another bug I'm forgetting somewhere

**Comment by nightpool** [comment] 2015-09-02 16:16
I was forgettting one—this is a dupe of #211

**Closed by nightpool** 2015-09-02 16:16 UTC
Labels: E-Editable Reblogs, unconfirmed
