### ISSUE TITLE
Posts look weird.

### ISSUE THREAD

**Issue by AuraSweet** [new-xkit/XKit#514] opened 2015-09-18 17:43 UTC
![why](https://cloud.githubusercontent.com/assets/14351360/9966485/737b815a-5dfa-11e5-8d94-8b2efd9c275a.png)
This only happens when I have text above, or below, not when I have both. It looks really weird, and it looks even worse on my blog. Worst yet, I can't get rid of it when I go back to edit the post.

**Comment by AuraSweet** [comment] 2015-09-18 17:57
I just disabled Editable Reblogs to check if that was what was wrong, and it is. Because once I disabled editable reblogs they looked normal.

**Comment by nightpool** [comment] 2015-09-18 18:25
creating/editing them looked normal, or did they just look normal automatically?

**Comment by AuraSweet** [comment] 2015-09-18 20:59
Creating them.

**Comment by anakhasilver** [comment] 2015-09-19 01:34
I can confirm this is a thing that happens when creating posts. If you edit them, they seem to fix themselves if this is the same issue I had, and I believe it is.

**Comment by dlmarquis** [comment] 2015-10-07 08:40
This looks like the image issue @blackjackkent fixed a while back. Closing until someone comes to tell me I'm wrong.

**Closed** 2015-10-07 08:40 UTC
Labels: E-Editable Reblogs, unconfirmed
