### ISSUE TITLE
Tag Tracking+ Not Updating All Tags

### ISSUE THREAD

**Issue by NuclearVacuum** [new-xkit/XKit#1193] opened 2016-10-25 03:11 UTC
The Tag Tracking+ extension is failing to notify me about updates. It continues to show my tags as being inactive, despite the opposite being true. This has been happening for almost a year now and is effecting 90% of my tracked tags (while always notifying me for one or two tags).

This is really annoying. I would appreciate any help I can get. Thank you.

**Comment by NuclearVacuum** [comment] 2016-11-03 01:02
Any help would be appreciated.

**Comment by NuclearVacuum** [comment] 2016-11-14 01:24
I would really appreciate a response. This has been going on for a year now. Please!

**Comment by nightpool** [comment] 2016-11-14 02:21
Unfortunately, we're not able to diagnose this issue with the amount of information given. Can you please provide:

 1. your operating system
 2. your XKit version
 3. your extension info dump (Other > Export Configuration > Extension Info Export)
 4. an example of a tracked tag that's not updating properly

thanks!

**Comment by NuclearVacuum** [comment] 2016-11-14 02:53
Thank you for your reply.

- My OS is Windows 8.1
- My X-Kit version is 7.7.4
- My extension dump is https://gist.github.com/55b6fca877293a1caf73e356003351ec
- An example tag is "Centepedle"

I do hope this helps.

**Comment by nightpool** [comment] 2016-11-14 15:25
@NuclearVacuum okay. "centepedle" doesn't seem to have had any posts in it since July 27th. The other tag you mentioned seems to be mostly NSFW posts, which I *believe* aren't returned by the API. This would probably be why it doesn't look like it's updating. The last non-adult post in that tag was 11/04.

**Comment by Wolvan** [comment] 2016-11-14 15:27
@nightpool is correct. NSFW posts are not returned by the API and thus can not be update checked. It also is the reason why the "new" tag for tags with the latest post being NSFW doesn't disappear

**Comment by NuclearVacuum** [comment] 2016-11-14 17:51
@nightpool @Wolvan Thank you for clarifying this for me. How do we go about fixing this?

**Comment by Wolvan** [comment] 2016-11-14 17:57
I did attempt to not use the api and make a request to the tag page but that ended up in such a horrible mess of resource hunger that I scrapped it soon after

**Comment by NuclearVacuum** [comment] 2016-11-19 20:31
Just wanted to know if there is any updates on this bug.

**Comment by Wolvan** [comment] 2016-11-19 20:53
This is not a bug and unlikely something we can fix unless we get another way of retrieving NSFW tags. @nightpool should we close this?

**Comment by nightpool** [comment] 2016-11-19 20:55
yeah, sorry, thought I had already closed this.

NSFW posts won't register for TagTracker. Non-NSFW posts should still work fine.

**Closed by nightpool** 2016-11-19 20:55 UTC
Labels: E-Tag Tracking+

**Comment by NuclearVacuum** [comment] 2016-11-19 21:03
What the hell? You guys seriously can't fix this? Why bother having a tag-tracking feature if it doesn't work half of the time? There's nothing you can do?

**Comment by nightpool** [comment] 2016-11-19 21:33
@NuclearVacuum please remain civil, and remember that XKit is a entirely supported by volunteers, who contribute in our free time. It doesn't look like this is possible to fix, given the restrictions imposed by tumblr staff. If someone has an idea on how to fix it, then we could consider implementing it, but it doesn't look possible right now.

**Comment by NuclearVacuum** [comment] 2016-11-19 21:46
@nightpool Please forgive me. I've been dealing with this issue for a year now. I've reached out to you guys for months, only to be snubbed. Now that I finally receive an answer, I'm told "nothing can be done now," and that the "matter is closed." You can understand my frustration with this.

At this point, I **HIGHLY** recommend you making this "bug" known to all of your followers. Making it clear to those wishing to use this app that it will not work for NSFW posts, so others are aware of this. From the way you guys are talking about it, I'm surprised it took me a year to even know about this. Please do this one thing.

**Comment by nightpool** [comment] 2016-11-19 21:55
@NuclearVacuum while I sympathize with the fact that you seem to be encountering some weird edge cases with Tag Tracker, the fact is that it works well for nearly all of our users. We've had a few bugs, but they've mostly been dealt with. This is the first time in the year and a half we've been running this project that someone has complained about tag tracker not working with NSFW posts, so I don't think the issue is severe enough to warrant a post on the main blog. I feel you that this information isn't messaged very clearly in the extension though, so I'll think about ways we can do that better.

While we're sorry that this issue sat unanswered for a month, the fact of the matter is that we're a very small team, with real life responsibilities, and we get very limited time to work on XKit. And most of that time is spent fixing severe bugs, not writing new features or answering support tickets. Because of the volume of users we have, we don't always have time to answer every support request individually.
