### ISSUE TITLE
Double posts

### ISSUE THREAD

**Issue by GrimmAx** [new-xkit/XKit#492] opened 2015-09-13 21:03 UTC
![refpic](https://cloud.githubusercontent.com/assets/14262640/9838971/7d0ce322-5a39-11e5-8707-cc6d771004cd.png)
Uninstalled and reinstalled XKit only to find that the issue is still happening. Any suggestions on how to fix it?

**Comment by ThePsionic** [comment] 2015-09-14 09:21
Closing as a duplicate of #100.

**Closed by ThePsionic** 2015-09-14 09:21 UTC
