### ISSUE TITLE
Xcloud local backup restoring remote extensions over local versions

### ISSUE THREAD

**Issue by Dhwty** [new-xkit/XKit#1392] opened 2017-08-13 20:52 UTC
Re the conversation in the support chat:

> penbrydd: I have a slightly munged version of Sidebar that works. But it's REPLACING IT, despite it having a much higher version number, with the latest version from the repo. 
> nightpool: even when you import from the local backup?
> penbrydd: Yes
> nightpool: This does seem to be a bug in xcloud though, so if you can file an issue for that, it would be great

1. Back up Xkit settings by doing an Xcloud *local* export. Backup includes two extensions that are slightly mangled versions of official extensions, with higher version numbers, so they shouldn't be replaced.
2. Upgrade from 7.7.5 to 7.7.7
3. Attempt to import local backup
4. Have Xcloud restore the current versions of those extensions from the repo instead of the backup versions.

Pretty sure that's not how that's supposed to work.

**Comment by Wolvan** [comment] 2017-10-26 12:49
That is how it is supposed to work. XCloud only backs up Settings, not the extensions themselves

**Comment by AprilSylph** [comment] 2019-09-29 15:23
not a bug, should be re-filed as an enhancement if anything; closing

**Closed by AprilSylph** 2019-09-29 15:23 UTC
Labels: E-XCloud, P-Papercut, bug
