### ISSUE TITLE
No Recommend Broken Again

### ISSUE THREAD

**Issue by turnonthe8track** [new-xkit/XKit#1927] opened 2020-07-20 23:09 UTC
No recommend is showing things on the "Tumblr Radar" again when it wasn't yesterday.

**Comment by AprilSylph** [comment] 2020-07-20 23:15
hiding the radar is an option in Tweaks, not No Recommended; there seems to be a race condition where if your dashboard loads slower than xkit does, this tweak won't work.

closing as duplicate of #1859

**Closed by AprilSylph** 2020-07-20 23:15 UTC
