### ISSUE TITLE
Full Config Export is broken

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1188] opened 2016-10-18 11:07 UTC
Always creates a gist containing just `{}`. We don't use it as much as the normal edump, but still not good that it's broken.

**Comment by nightpool** [comment] 2016-10-18 12:42
This is just chrome, and there's a pr I was just looking at the other day
that fixed it. The problem is that gm_listValues returns nothing. The other
problem is that the entirety of xkit storage needs to be rewritten from the
ground up, so.

tags: B-Chrome, bug, P-Medium

**Comment by AprilSylph** [comment] 2018-06-17 15:47
resolved by #1536

**Closed by AprilSylph** 2018-06-17 15:47 UTC
Labels: B-Chrome, B-Firefox, E-XKit Main, P-Medium, bug
