### ISSUE TITLE
J/K Across Pages triggering in the messaging window

### ISSUE THREAD

**Issue by nightpool** [new-xkit/XKit#1386] opened 2017-08-09 19:51 UTC
from the ask box 

> Not sure if it's an Xkit issue or not, but I haven't been able to find any similar issues when Googling the problem. Using Chrome, Tumblr keyboard shortcuts are interrupting typing in the messaging window. Specifically, the K previous post shortcut is activating while attempting to type in the messaging window. The only work around I've been able to come up with if to refresh to the top of my dash. I still get the "Already at first page" popup, but I can at least continue typing the message.

**Comment by AprilSylph** [comment] 2018-03-17 18:08
dupe of #1061

**Closed by AprilSylph** 2018-03-17 18:08 UTC
Labels: E-J/K Across Pages, unconfirmed
