### ISSUE TITLE
Firefox is automatically disabling xkit

### ISSUE THREAD

**Issue by clarafolb** [new-xkit/XKit#872] opened 2015-12-17 00:41 UTC
Firefox just today decided that xkit is unsigned and untrustworthy. Apparently the only way to get Firefox to enable it is to completely turn off checking for whether extensions are trustworthy or not. What can I do and is xkit working on this problem?

**Comment by TigerwolfSpellbear** [comment] 2015-12-17 02:03
I am also wondering the same thing. Quite an annoying surprise from Firefox!

**Comment by Somariel** [comment] 2015-12-17 02:24
This appears to be something new with Firefox 43.0 and on, done in the name of protection against malware and browser hacking. Info about what Firefox has done is at this link: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox
and info about how xkit can get signed is at this link: https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by clarafolb** [comment] 2015-12-17 02:32
Yeah, I suppose what I was wondering the most out of this is whether xkit was planning to get getting signed so that this doesn't happen. I'm not sure I like having to totally disable a security measure in order to use xkit, which is pretty much what makes Tumblr usable. That said, I really wish Firefox would have included a whitelist so I don't have to.

**Comment by nightpool** [comment] 2015-12-17 02:47
Hey guys we've been working with Mozilla for a few months to get XKIT
signed, but there are still a few things they're dragging their feet on,
related to the underlying technical design of the extension. We're hoping
to have a working version within a week, but it depends in developer
availability which is always a gamble close to Christmas.

Stay tuned, we'll keep you guys up to date as things develop.

**Comment by nightpool** [comment] 2015-12-19 20:19
dupe of #216

**Closed by nightpool** 2015-12-19 20:19 UTC
