### ISSUE TITLE
Unable to use plugin.

### ISSUE THREAD

**Issue by nuke-annihilation** [new-xkit/XKit#878] opened 2015-12-19 17:08 UTC
Latest FireFox (43.0.1) complains about unverified plugin, and refuses to enable XKit.
![nxkit](https://cloud.githubusercontent.com/assets/355687/11914248/b77c62fa-a640-11e5-87f5-f5138dd6f462.PNG)

**Comment by culturalrebel** [comment] 2015-12-19 17:37
I'm having the same problem.  My FireFox updated automatically and as soon as I opened it up, the same error message came up.

**Comment by ThePsionic** [comment] 2015-12-19 18:08
Firefox stopped allowing Addons Mozilla did not sign starting from Firefox v43. We are doing our best to get signed ASAP, but it's a rather lengthy process.

In the meantime there are multiple workarounds:
1. Use another Browser like Chrome or Opera with New XKit (recommended)
2. Downgrade Firefox to v42
3. Disable signature checks in Firefox v43 (NOT recommended)

WARNING! THIS IS A SECURITY MEASURE PUT IN BY MOZILLA. DISABLING THIS MIGHT PUT YOU AT RISK OF VIRUSES OR ADWARE! If you still want to proceed, type "about:config" in your Adress/Search Bar, look for "xpinstall.signatures.required" and double click on it so it has the value "false".

**Comment by nightpool** [comment] 2015-12-19 20:19
dupe of #216

**Closed by nightpool** 2015-12-19 20:19 UTC
