### ISSUE TITLE
OCP-FORMKEYREQFAIL08

### ISSUE THREAD

**Issue by wooziwoozi** [new-xkit/XKit#1561] opened 2018-05-30 11:42 UTC
I recently switched back to FireFox, and no matter what I do I get this error when trying to queue from one click postage. I am not sure if its broken, if FireFox is the issue, or if I am doing something wrong.

ETA: I am using FireFox 60.0.1 and New Xkit 7.8.2 Patches v. 6.11.1

**Comment by AprilSylph** [comment] 2018-05-30 17:22
This error will always occur when using SessionBox or a Firefox Container Tab. Hopefully, this will be resolved by fixes I'm pushing in #1536.

**Comment by wooziwoozi** [comment] 2018-05-30 21:36
How do I find out if I am using a session box or a container tab? I am right clicking everything and can't find these words.

**Comment by AprilSylph** [comment] 2018-05-31 04:33
Hmm, can you reblog things normally? If you're not using a container tab I have to assume it's another Firefox add-on you're using, since I can't reproduce this.

**Comment by wooziwoozi** [comment] 2018-05-31 05:46
Oh, they are add-ons. No wonder I couldn't find it. I guess I will did though and see if one is causing it. I forgot that that may be the issue.

Okay I am confused. I un-enabled all my add-ons, then re-enabled one by one and..... now it is working.....? But then I restarted my browser and it was wonky again so I have no idea, but it does seem add-on related maybe.

I will just leave a list of what I have installed in case you wish to run your own tests:
https://addons.mozilla.org/en-US/firefox/addon/download-statusbar-webext
https://addons.mozilla.org/en-US/firefox/addon/downloads-sidebar
https://addons.mozilla.org/en-US/firefox/addon/ghostery
https://addons.mozilla.org/en-US/firefox/addon/honey
https://addons.mozilla.org/en-US/firefox/addon/imagus
https://addons.mozilla.org/en-US/firefox/addon/keepa
https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager
https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current
https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite
https://addons.mozilla.org/en-US/firefox/addon/stylish
https://addons.mozilla.org/en-US/firefox/addon/tampermonkey
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin

**Comment by AprilSylph** [comment] 2018-05-31 06:10
Ghostery is a pretty common problem-causer and very helpfully only starts to cause problems after being enabled a while. You may want to consider alternatives like Privacy Badger.

issue closed; confirmed as add-on conflict

**Closed by AprilSylph** 2018-05-31 06:10 UTC
