### ISSUE TITLE
Block notifications doesn't work with Activity+

### ISSUE THREAD

**Issue by Schmaiffe** [new-xkit/XKit#113] opened 2015-08-03 02:20 UTC
I can still see the button to block notifications on the original post, and it shows as selected, but the notifications still show up on my activity feed. (I have notifications turned off on my dash.) I don't get anything on the notifications that lets me block the post either, I have to have the post on the tumblr.com/blog/[myblog] view. (Fun since the post is from literally two years ago, why is it getting notes now lol.)

Using Firefox 39 on Windows 8.1.

**Comment by mackenbrose** [comment] 2015-08-04 00:16
I'm not sure if you've seen this, but I posted a solution of sorts at my tumblr (http://mackenbrose.tumblr.com/post/118721212682/notification-block-fix). I first figured this out months ago when the original coding went glitchy and xkit guy left. So far it seems to be holding up for me. I still have the OLD xkit so far though and I use Chrome, but it's the same coding so it should work for Firefox.

I hope this helps you and whoever the awesome enough to be fixing xkit :)

**Comment by Schmaiffe** [comment] 2015-08-04 00:36
Thank you for the reply! I had not seen that, and I just tried it, but sadly the notifications are still on my activity page. I double-checked that the post is blocked, even unblocked and reblocked it, but it still shows up. I am using the new xkit, though the code did look the same and I found the bit in your post without any problem.

**Comment by mackenbrose** [comment] 2015-08-04 00:49
My only other advice is double check to make sure the preference pane logo is loaded (sometimes that doesn't load and my notifications don't get blocked because it's still slow as heck). Also. Question-- do you have Activity+ installed? (and if so after you follow the tutorial, make sure "group notifications by post" is unchecked. This is a super important thing as that function screws with NotificationBlock) 

I finally got Firefox to DL new xkit (i guess i had a suuuuuper old version lol) so I'll play around and see if I can come up with a solution if none of the other things work.

**Comment by Schmaiffe** [comment] 2015-08-04 00:53
Oh! So, I didn't think I had Activity+ installed, but I checked and it was installed but the button to activate it was unchecked since I never use it. I uninstalled it and it's working now, thank you!

**Comment by blackjackkent** [comment] 2015-08-10 19:54
To confirm -- this bug is resolved?

**Comment by nightpool** [comment] 2015-08-10 20:03
@blackjackkent we should probably fix activity+ so it works with
notification block.

**Comment by blackjackkent** [comment] 2015-08-10 20:17
Ah -- gotcha, misread the situation. :+1:

**Comment by ThePsionic** [comment] 2015-11-06 15:27
Unable to reproduce on Firefox, closing. @Schmaiffe @mackenbrose if you have any issues with this still, feel free to re-open.

**Closed by ThePsionic** 2015-11-06 15:27 UTC
Labels: E-Activity+, E-NotificationBlock
