### ISSUE TITLE
Find Inactives new feature

### ISSUE THREAD

**Issue by xThreeh** [new-xkit/XKit#861] opened 2015-12-09 01:34 UTC
I would suggest the next improvement for this extension.
↓ ↓ ↓ ↓ ↓ NEW VERSION ↓ ↓ ↓ ↓ ↓
![nuevoscreenshot_63](https://cloud.githubusercontent.com/assets/16139465/11673632/2d270c12-9df9-11e5-9a5f-d9fc8af78b68.jpg)
↓ ↓ ↓ ↓ ↓ OLD VERSION ↓ ↓ ↓ ↓ ↓
![screenshot_63](https://cloud.githubusercontent.com/assets/16139465/11673626/2467035c-9df9-11e5-9bad-8399ad196272.png)

This change will make it easier to unfollow blogs that are inactive, as currently in need to go to each of them to unfollow
P.S: Excuse my English, I speak Spanish but I try to help.

**Comment by Wolvan** [comment] 2015-12-09 01:37
See #696 
Duplicate of #189

**Closed by Wolvan** 2015-12-09 01:37 UTC

**Comment by xThreeh** [comment] 2015-12-09 01:43
@Wolvan 
Thank you, I had no idea that he had already suggested and taught today while my girlfriend to use xkit I happened to this

**Comment by Wolvan** [comment] 2015-12-09 01:58
It's alright, no worries! #169 is pretty old, I can see why you closed a new issue

**Comment by nightpool** [comment] 2015-12-09 05:00
*created

**Comment by Wolvan** [comment] 2015-12-09 05:34
created, yeah, thank you
