### ISSUE TITLE
Profiler extension

### ISSUE THREAD

**Issue by cookiesss** [new-xkit/XKit#869] opened 2015-12-13 20:33 UTC
Hello! The Profiler extension isn't working anymore or the "i" on a blog won't show up at all and sometimes the bottons on top (Follow, Unfollow, Reblog, etc.) disappear at random

**Comment by nightpool** [comment] 2015-12-13 21:28
dupe of #831. 

(see http://new-xkit-extension.tumblr.com/post/134701011764/blog-controls)

**Closed by nightpool** 2015-12-13 21:28 UTC
