### ISSUE TITLE
tweaks extention not working

### ISSUE THREAD

**Issue by Davth** [new-xkit/XKit#1790] opened 2020-04-08 16:09 UTC
on firefox windows 7(don't know if that's important) the tweaks extension just stopped working, no longer dose it hide the radar and recommended blogs, i tried resetting setting, uninstalling the widget, and nothing. I'm not sue if it's a few options or all, but I can tell you those for sure, have just stopped working all together

**Comment by AprilSylph** [comment] 2020-04-08 16:10
Tweaks has not been updated for the new dashboard yet. Please see our post: https://new-xkit-extension.tumblr.com/post/613164737228832768/

closing as duplicate of #1770

**Closed by AprilSylph** 2020-04-08 16:10 UTC

**Comment by Davth** [comment] 2020-04-08 16:38
sorry, but the post you linked doesn't say anything about TWEAKS itself, so i'm still a little confused

**Comment by AprilSylph** [comment] 2020-04-08 16:53
> the new web interface is entirely new, written from the ground up, and thus, XKit doesn’t work on it

this includes all XKit extensions, including Tweaks. All extensions are broken by default on the new dashboard - we have fully updated Old Blue, and only partially updated XKit Preferences, One-Click Postage and Anti-Capitalism. All other extensions are not expected to work until we update them.
