### ISSUE TITLE
Reblog Display Options Acting Odd

### ISSUE THREAD

**Issue by pwnedoscar** [new-xkit/XKit#641] opened 2015-10-15 02:11 UTC
This screenshot was taken with the Style set to Flat, and the default options set.
![new bitmap image](https://cloud.githubusercontent.com/assets/15134074/10502800/5f58bcea-72b5-11e5-9cb6-0f003c784c30.jpg)
I think this is what Nested style is supposed to look like, based on the way the post described it.

This screenshot was taken of the same post, after Style was set to Nested, with no other options.
![new bitmap image](https://cloud.githubusercontent.com/assets/15134074/10502970/1b75d6aa-72b7-11e5-89e8-5c186f96a3f5.jpg)
Everything that would be underneath a blockquote reblog chain disappears.

Upon hitting the reblog button, everything in the blank post appears, as normal.

For whatever amount it helps, this is using Google Chrome on an HP laptop, and I made certain that Editable Reblogs was deactivated.

**Comment by nightpool** [comment] 2015-10-15 02:44
Please refresh the page after changing between flat and nested.

**Comment by Wolvan** [comment] 2015-10-15 02:50
From support chat:
<ajking324> Heya. I'm having this problem with the new reblog display options extension where when it's in Nested mode the contents of the post don't really show up (at least some of them) I was wondering if anyone else was having this problem?
<ajking324> https://www.filepicker.io/api/file/EhURgRsKTJa0bWYheeRo
Wolvan: and you set you did refresh?
<ajking324> yup. when i refresh it shows up for a second (before xkit is loaded) then disappears

**Comment by nightpool** [comment] 2015-10-15 02:53
I can't reproduce this on my end, unfortunately. Do you have any other
stylish extensions or anything installed?

**Comment by Wolvan** [comment] 2015-10-15 02:54
@nightpool Person already left, sadly. They said they are going to check back, maybe we can get that information then

**Comment by Merunari** [comment] 2015-10-15 03:05
I'm having the same issue in Firefox. I haven't tried Chrome yet. In addition to reblog display options, I have these extensions installed: activity+, alternative timestamps, anti-capitalism, audio+, audio downloader, classic search, drafts+, editable reblogs, enhanced queue, iconified notifications, mass+, mass deleter, no recommended, notifications+, one-click postage, one-click reply, tweaks, outbox, quick tags, read more now, reblog as text, reblog yourself, tag replacer, tag tracking+, themes+ (preview), user menus+ and xinbox. I have nothing installed via Stylish or GreaseMonkey.

**Comment by Merunari** [comment] 2015-10-15 03:21
Just went through and disabled everything except for reblog display options and I'm still having the issue. At this point, there should be absolutely nothing interfering with it. No Stylish extensions, no GreaseMonkey scripts and no other xkit extensions enabled but the quote chain still doesn't appear on the dash.

**Comment by anakhasilver** [comment] 2015-10-15 05:02
I can vouch for the same steps Merunari did. Nothing works.

**Comment by configchan** [comment] 2015-10-15 05:19
It happens because some posts are missing the .reblog-list div, and have the contents sitting loose in the .post_container div. If you remove the code to make it return without doing anything if that div is missing, it works completely fine.

This only happens with reblog chains that have been mangled in such a way that they don't get parsed properly by Tumblr's new layout code, and end up looking kind of like the old nested style as in the example by the ticket opener.

**Comment by komikbookgeek** [comment] 2015-10-15 05:50
I'm in Chrome and having the same issue. How would we remove the code if it's something on our dash? Or period?

**Comment by configchan** [comment] 2015-10-15 05:53
I mean the opening the code for the better_reblogs extension and removing that line. The parsing issue is on tumblr's end, but the problem with it being deleted is obviously on XKIT's end, since it only happens when you use this extension in this setting.

**Comment by Wolvan** [comment] 2015-10-15 08:47
Yeah, we suspected it to be other scripts that have messed up the post already, good to know that it really is the case and nothing that is part of pure xkit. We'll look into this, @configchan can you give us the line nr?

**Comment by configchan** [comment] 2015-10-15 09:36
The conditional block from line 193 to 195 is the one that causes the issue. I'm guessing the conditional is meant to terminate the function in order to stop it doing anything bad if the post isn't a reblog, but nothing it does in said circumstance causes any issues. Everything it does until the last two lines pf the function amount to nothing, and the last two lines end up taking care of this fringe case (which seems to be the entire problem in the first place, the last two lines not executing in this fringe case).

**Comment by Wolvan** [comment] 2015-10-15 09:39
That's good to know, I'll talk with @nightpool about removing those lines. Thanks a lot for your help, @configchan

**Comment by configchan** [comment] 2015-10-15 09:49
No worries! Glad to be of help!

**Comment by nightpool** [comment] 2015-10-15 15:05
I'm still in the middle of finals week, but I'll try to get a new version
of br pushed out sometime this weekend or next week.

**Comment by maswartz** [comment] 2015-10-18 19:44
I believe this has been happening to me too. With me it happens usually when I reblog a picture post and I put a caption, the caption doesn't show up on my dash but when I go to edit it it appears, it even shows up if I reblog it from myself. The strange thing is it has happened to someone else on my dash. The caption didn't show up on my dash under their post but it showed up under mine when I reblogged it.

**Comment by nightpool** [comment] 2015-10-19 01:16
Pretty sure this is fixed on local copy and I *should* have tune later this
week to look into stuff (but no promises)

Someone mind assigning me? Thx

**Comment by Wolvan** [comment] 2015-10-19 01:26
@nightpool you have been asigned

**Comment by dlmarquis** [comment] 2015-10-20 17:46
This *might* be fixed by #650. It should fix @maswartz's issue, at least.

**Comment by maswartz** [comment] 2015-10-20 17:47
@dlmarquis thanks

**Comment by configchan** [comment] 2015-10-21 04:17
It will not fix the issue in the cases I refer to, as if the div I mentioned is missing, the edited code will still return prematurely.

**Comment by nightpool** [comment] 2015-10-24 17:53
fix for this coming out today, thanks everyone

**Closed** 2015-10-24 18:51 UTC
Labels: E-Reblog Display Options, needs review
