### ISSUE TITLE
Add "selective dashboard" extension

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#1142] opened 2016-08-28 11:07 UTC
``` txt
XKit|37777 (Completely understand if you guys have enough on your plate!)
XKit|37777 Oh great.
XKit|37777 I was just wondering if you'd thought about an extension feature that allows you to sort of sub-categorise the content you want to see on your dashboard?
XKit|37777 For example...
XKit|37777 I have a couple of side-blogs, so I follow different blogs relevant to the blogs I run
XKit|37777 Sometimes I want to be able to see JUST those partciular blogs, ie. photography blogs for my photography blog
XKit|37777 or, for example, someone might just want to see Japanese culture related blogs for the anime blog
ThePsionic Hm, that would require manual tagging of each blog by the user most likely
XKit|37777 Yes
```

Technically possible? No idea. Good idea? Definitely.

**Comment by nightpool** [comment] 2016-10-13 17:59
I would LOVE this but it seems pretty freaking hard to do well.

**Comment by AprilSylph** [comment] 2018-03-17 18:37
dupe of #319

**Closed by AprilSylph** 2018-03-17 18:37 UTC
Labels: enhancement
