### ISSUE TITLE
Mozilla has taken New XKit down from addons.mozilla.org

### ISSUE THREAD

**Issue by lavacano201014** [new-xkit/XKit#775] opened 2015-11-16 22:02 UTC
The link 404s and the extension does not appear in search.

**Comment by nightpool** [comment] 2015-11-16 22:10
Yeah we're working on it. Had a busy morning today in xkit chat!

see #772 and #773

@hobinjk what's our status on getting relisted? anything yet for us to do or just biding our time until we hear back from mozilla?

**Comment by hobinjk** [comment] 2015-11-16 22:13
@nightpool I think all we can do is wait. The review queue appears to actually be moving, which is hopeful. I'll try responding to the email to see if there are other options.

**Comment by lavacano201014** [comment] 2015-12-16 20:03
As of Firefox 43, Firefox by default disables the installation and usage of unsigned extensions. They can be reenabled with an about:config option (xpinstall.signatures.required), but no telling how long that will remain the case. I'd really prefer that Firefox doesn't become a locked-down walled garden like Chrome has, but that's out of everyone's hands at this point.

Any news about the addons.mozilla.org reviews?

**Comment by Wolvan** [comment] 2015-12-16 20:31
We got rejected weeks ago. Using eval in New XKit completely disqualifies from having a chance to be signed.

We are currently working on an eval-less version

**Comment by nightpool** [comment] 2015-12-16 21:08
Cross our fingers and knock on wood but we should have a signed extension
hopefully this time next week. I'll have a lot of time to work on it after
finals finish on Friday. (And @hobinjk has already been working on a test
build)

**Comment by nightpool** [comment] 2015-12-19 23:11
dupe of #216

**Closed by nightpool** 2015-12-19 23:11 UTC
Labels: B-Firefox
