### ISSUE TITLE
When clicking avatars, open blog in new tab and disable that weird sideblog thing that comes up.

### ISSUE THREAD

**Issue by PeachyBird** [new-xkit/XKit#381] opened 2015-08-28 05:54 UTC

**Comment by ThePsionic** [comment] 2015-08-28 07:31
The Open in New Fab extension has an option for this, unless I am
misunderstanding.

**Comment by Dhwty** [comment] 2017-07-02 20:32
This is either fixed by Open in New Tab or it's caused by someone setting their blog to private (which xkit can't do anything about, per #1094 ). Either way, this issue is probably dead.

**Closed** 2017-07-02 20:33 UTC
Labels: unconfirmed
