### ISSUE TITLE
Editable Reblogs removes captions sometimes

### ISSUE THREAD

**Issue by ThePsionic** [new-xkit/XKit#261] opened 2015-08-14 00:04 UTC
>((editable reblogs extension will delete captions on photos/photosets and some text posts but not all. this generally happens when i reblog in a new tab, but has happened from main dash tab. i know it's a third party extension but ya'll got something in the works about this? or is it just my version of firefox??))

**Comment by nightpool** [comment] 2015-08-14 14:35
dupe of #211

**Closed by nightpool** 2015-08-14 14:35 UTC
Labels: B-Firefox, E-Editable Reblogs, unconfirmed
