### ISSUE TITLE
One-Click Reply username is undefined

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#158] opened 2015-08-07 05:12 UTC
Many asks are reporting this:
> Hello! I'm experiencing a small problem with the One-click reply app on Chrome. the main functionality is fine, but whatever blog that I'm replying to would show up as "undefined" in the text post, and would be tagged as "undefined" as well. is this a known issue? Is there something I'm doing wrong? Thank you!

**Comment by hobinjk** [comment] 2015-08-07 08:10
Unable to reproduce on Chrome

**Comment by WyohKnott** [comment] 2015-08-07 08:16
If you do it from the "Notes popup", it shows undefined, we already got a bug report for this: https://github.com/new-xkit/XKit/issues/82

**Comment by blackjackkent** [comment] 2015-08-07 15:46
Duped this on Chrome; I can look into this this evening if no one else already is.

**Comment by nightpool** [comment] 2015-08-07 16:28
@blackjackkent that would be great.

**Comment by nightpool** [comment] 2015-08-07 17:39
closed as a dupe of #82.

**Closed by nightpool** 2015-08-07 17:40 UTC
Labels: E-One-Click Reply
