### ISSUE TITLE
XKit does not pass automated validation

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#216] opened 2015-08-11 21:31 UTC
https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews prohibits "remote JavaScript execution or injection" which is 95% of what we do

**Comment by nightpool** [comment] 2015-08-11 21:48
tying our extensions to the full addon review process would make it
incredibly hard for us to react to tumblr changes in the way people expect
us to. Is there no way we can get an exception from mozilla? How many
firefox installs do we have?

**Comment by 0xazure** [comment] 2015-08-11 21:49
Adding this here for reference:

http://browserify.org/ is a pretty good option if we're going to pack everything in. CommonJS module syntax would let us to a lot more modular code, and take advantage of https://www.npmjs.com/ instead of [embedding things directly](https://github.com/new-xkit/XKit/blob/8e8534bab12d95ca841537581ebf2c3803167f14/Extensions/xcloud.js#L1148-L1202).

**Comment by blackjackkent** [comment] 2015-08-11 22:04
According to https://addons.mozilla.org/en-US/firefox/addon/new-xkit/ we have 6250 FF users.

I and @0xazure (whichever of us gets to it first) are going to look into a POC of an approach that won't require eval()ing the extensions, but @nightpool 's point is a good one.

**Comment by dlmarquis** [comment] 2015-08-11 22:07
If we wanted to be truly insane, we could have a signed and an autoupdate version for Firefox. Although given the attitude of our users I think it's better to remain unsigned than to slow updates down that much.

**Comment by Wolvan** [comment] 2015-08-11 22:12
@dlmarquis If I might put my 5ct into this, even though I am not using firefox personally: I'd say signing XKit would be something we should aim for. But not yet. There are a lot of bugs still in the code which we should fix, but after we achieved a proper, stable and working version of everything that makes up XKit we should definitely look into getting the extension signed

**Comment by hobinjk** [comment] 2015-08-11 22:19
@Wolvan The problem is that the running of unsigned extensions will be prohibited (with an about:config workaround) starting in Firefox 41. The workaround will be removed in Firefox 42, leaving all people on Release and Beta builds of Firefox unable to run unsigned extensions.

Firefox 41 will be released 6 weeks from now

**Comment by Wolvan** [comment] 2015-08-11 22:22
@hobinjk Wait really? Mozilla is going the google route and blocking extensions as well now?
Then we gotta hurry up a lot to get this shit going. And apologize to the Firefox users that updates will, from then on, be a lot slower

**Comment by dlmarquis** [comment] 2015-08-11 22:24
I'm surprised it's so soon given how long it takes to even get signed.

**Comment by Wolvan** [comment] 2015-08-11 22:25
And we can't start the signing process now because we still use eval. This blows

**Comment by dlmarquis** [comment] 2015-08-11 22:55
Perhaps we could have Firefox users paste in autoupdate code à la Greasemonkey? Since I can't imagine Mozilla banning Greasemonkey anyway.

**Comment by Wolvan** [comment] 2015-08-11 22:58
but greasemonkey DOES update it's scripts automatically. How do Greasemonkey scripts get injected into the page if not EVAL?

**Comment by dlmarquis** [comment] 2015-08-11 23:02
Greasemonkey might have to change their code. Or maybe they have enough clout with over 1 million users that Mozilla will loosen its policies (PLEASE). We could probably benefit from digging around in their source.

**Comment by Wolvan** [comment] 2015-08-11 23:13
If we do it like greasemonkey does, we should be guaranteed to get signed if they do. If not, we can complain to them that GM did

**Comment by dlmarquis** [comment] 2015-08-11 23:13
Also doesn't Adblock Plus autoupdate its blacklist? That's got over 19 million users.

**Comment by Wolvan** [comment] 2015-08-11 23:15
The Blacklist is not javascript though, is it?

**Comment by blackjackkent** [comment] 2015-08-11 23:15
Isn't the issue less whether we can get signed (since we have ideas about refactoring our external injection) and more about whether our updates will be released to users in a timely fashion post-signing?

**Comment by dlmarquis** [comment] 2015-08-11 23:16
The issue is how do we get signed without accidentally creating 6,000+ Chrome converts, I think. Ideally we'd be able to update quickly and be signed.

**Comment by 0xazure** [comment] 2015-08-23 13:37
Putting this here for reference (especially around timelines): https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/ thanks to @bvtsang 

Would be good to start adding GitHub milestones for these dates.

**Comment by nightpool** [comment] 2015-12-19 20:20
@hobinjk can you post publicly the WIP version you have so I can review it? is there a branch for it?

I'm down to crunch out whatever remaining code we have to implement today/tomorrow.

**Comment by nightpool** [comment] 2015-12-19 20:21
the goal here is to get us passing automated validation, so we can use `jpm sign` to publish new extension versions.

**Comment by hobinjk** [comment] 2015-12-19 20:38
@nightpool https://github.com/hobinjk/XKit/tree/firefox-no-eval

**Comment by nightpool** [comment] 2015-12-19 23:13
@hobinjk mind pushing that to the a branch on the org repo so I can work on it? I have time now to get it cleaned up. (i.e. we should add messaging that indicates they're probably going to get slower updates then others)

is there an offline validator tool or do I have to use the online one? I don't have access to the online one for xkit iirc.

**Comment by lavacano201014** [comment] 2015-12-20 22:15
I said this in #775 already, but for reference here since this seems to be the main one:

A temporary workaround is to open about:config and set xpinstall.signatures.required to false. I don't know how long that feature will last, or how well Tumblr will receive such instructions in the meantime, but Firefox is not *entirely* XKit-less at the moment.

(Also, I'm noticing that there seem to be about:config switches related to a signature whitelist - perhaps users can add public keys to that list and XKit can self-sign? Perhaps this is a feature for a later version?)

**Comment by nightpool** [comment] 2015-12-21 05:28
Hey @lavacano201014! thanks for your comment, but that switch will not be a long-term solution—it disappears in the next Firefox version

this is just an internal dev thread about getting done the work necessary to get XKit automatically signed.

**Comment by hobinjk** [comment] 2015-12-21 05:41
@nightpool Pushed to https://github.com/new-xkit/XKit/tree/firefox-automatic-signing

**Comment by nightpool** [comment] 2015-12-21 05:47
@hobinjk what are you using for testing validation? the addon-linter project doesn't seem to be matching https://addons.mozilla.org/en-US/developers/addon/validate for me (doesn't warn about evals, for one)

**Comment by hobinjk** [comment] 2015-12-21 05:52
@nightpool That's what I use, with "Do not list my add-on on this site" checked. It shows 26 warnings, starting off with complaining about setInterval.

**Comment by nightpool** [comment] 2015-12-21 06:01
@hobinjk I just uploaded the current XKit extension, and it has 14 warnings, (starting, obviously, with "don't use eval" or w/e) and says "your extension will be automatically signed" is this an issue with the standalone validator?

**Comment by nightpool** [comment] 2015-12-21 06:02
![image](https://cloud.githubusercontent.com/assets/233815/11924406/201e9144-a776-11e5-8730-00123ea18725.png)

**Comment by nightpool** [comment] 2015-12-21 06:04
Looks like this is a miscommunication: https://github.com/mozilla/olympia/blob/master/static/js/common/upload-addon.js#L434-L436 implies that "your extension will be automatically signed" means "your extension will be automatically signed, IFF it passes the automated signer"

:/

**Comment by hobinjk** [comment] 2015-12-21 06:07
I also see that. It's unfortunate that that is a miscommunication.

The target I've been shooting for is 0 warnings (or as close to 0 warnings as possible).

**Comment by nightpool** [comment] 2015-12-21 06:45
as of December 1st, addons no longer need to pass the validator to be signed: https://blog.mozilla.org/addons/2015/12/01/de-coupling-reviews-from-signing-unlisted-add-ons/

while I'm incredibly upset with mozilla for not communicating this to us better, this provides a clear path forward for XKit. We should have a signed version out in the next few hours.

not closing this issue because we do want to be back in AMO eventually.

**Comment by nightpool** [comment] 2016-09-14 21:28
closing this issue because its super old

**Closed** 2016-09-14 21:28 UTC
Labels: B-Firefox, enhancement
