### ISSUE TITLE
Editable Reblogs posts twice?

### ISSUE THREAD

**Issue by obsessionssL** [new-xkit/XKit#859] opened 2015-12-08 04:22 UTC
I noticed that with the editable reblogs 3.0.4 puts the caption or post twice for some reason.
![1](https://cloud.githubusercontent.com/assets/14366224/11647700/42e9aa8e-9d39-11e5-885a-6908f0e4cd9d.JPG)
![2](https://cloud.githubusercontent.com/assets/14366224/11647699/42e99efe-9d39-11e5-8a91-1bd87661b5db.JPG)
 Both of these pictures should be one after the other when you scroll down..

**Comment by citrusella** [comment] 2015-12-09 20:45
[I've had this problem](https://github.com/new-xkit/XKit/issues/497) (or what I think is this problem) with previous versions of ER. Does it happen during the initial reblogging in the post window or is it only present after you save the post somehow? Does it happen on all posts?

**Comment by obsessionssL** [comment] 2015-12-09 22:02
It happens when I initially reblog and when I save it as a draft.
And I do not even have Old Stats extension added to my xkit

**Comment by citrusella** [comment] 2015-12-10 00:30
Okay. (Funnily enough, though now this feels like a different issue than mine due to it happening before the post is saved as well, I feel like I remember disabling Old Stats didn't fix it. ...I don't know nothing about writing no extensions. XP)

**Comment by nightpool** [comment] 2015-12-10 01:54
Can you post your extension info dump? Thanks! You can find it in the other
tab > Export Configuration

**Comment by citrusella** [comment] 2015-12-10 04:01
I'll assume you're talking to me, since I'm quoted in your message. I haven't used ER in awhile, in all honesty, because every time I've switched it on, it's eventually hit the issue, so my list might not reflect a current issue (I can switch it on now and see if I eventually run into the issue, but in terms of what I was talking about, I was referring to the last time I had ER switched on): https://gist.github.com/3cfd6f402c6e657e72c4 (Lethe, Old Stats, Soft Refresh, No Sidebar, and Edible Reblogs are installed but disabled--I'm actually about to uninstall old stats since I'm using Old Sidebar now; ER is also technically disabled as of this writing). Dunno how helpful this is since I'm not sure if I'm currently having the same issue (or the old issues), but figured I'd follow through with your request.

If you weren't actually replying to me... oops, sorry!

**Comment by floofins** [comment] 2015-12-29 09:02
I'm also having this problem! My Xkit extensions include:  Xinbox, One-click postage, One-click reply, Tweaks, Go To Dash, Editable Reblogs, Lethe, Blacklist, Notification Block, Pokes, Post Crushes, Post Archiver, Shorten Posts.

**Comment by nightpool** [comment] 2015-12-29 17:12
@citrusella Old Stats is the cause of this issue.

@floofins please post an extension info dump—I mentioned how to post them
in my last message

**Comment by citrusella** [comment] 2015-12-29 19:52
@nightpool Even if it's not enabled? 0_o (Granted, I know nothing of the internals of XKit, so... I mostly just ask stupid questions.) I guess since it's been uninstalled for awhile on my configuration, at any rate, I could stop cowering in ER's presence now. XD

**Comment by floofins** [comment] 2016-01-17 04:42
@nightpool Here you go: https://gist.github.com/d79ca187aaefc29b627f

**Comment by nightpool** [comment] 2016-10-13 19:17
Should be fixed in most recent ER, AFAIK

**Closed by nightpool** 2016-10-13 19:17 UTC
