### ISSUE TITLE
Notes popup caps popular posts to ~400 notes

### ISSUE THREAD

**Issue by cmmac** [new-xkit/XKit#1003] opened 2016-03-25 15:23 UTC
After a post hits 1,000 notes, it suddenly only shows approximately 400 of them. This only affects posts about 2 months old or newer, older posts haven't been affected yet, but that's probably likely to change over time.

This prevents ReplyViewer and TagViewer from loading more then a few replies and tags.

-----
*original description:*
Whenever I use tag viewer it only displays about 10 peoples tags and then won't load any further.

**Comment by malvinando** [comment] 2016-03-26 01:34
Same thing is happening to me, and with both TagViewer and ReplyViewer. I asked some people, but it seems like it's working fine for most of them. Only a few said the same thing was happening to them. I have no idea of what could be causing this... which is a real bother, since it's way easier to keep track of my posts through these two extensions than manually.

**Comment by AlyoshaVasilieva** [comment] 2016-03-26 02:57
This is not the fault of xkit. If you click Notes on something (instead of using TagViewer) and scroll down it will eventually suddenly go to the original note of the source now. So TagViewer can only check maybe a couple hundred blogs. Tumblr change or bug.

Or it might be rate-limiting targeting retags/tagviewer because Tumblr is annoyed at it, for some reason.

**Comment by nightpool** [comment] 2016-03-26 03:45
Yes this is an issue with the notes popup in general. It affects non-xkit
users as well.

So far we have no concrete information into what is happening or why.

**Comment by harrie5** [comment] 2016-03-28 17:10
Hey! So tumblr just released their new reply update, and not everyone has it yet, so:
They've reorganised the notes popup so the list is the other way around, which is why it started to load the original source so quickly I think? Bugs caused by them getting ready to release the new update.

I've made a quick post covering the changes here: [[http://captainharrie.tumblr.com/post/141840449415](http://captainharrie.tumblr.com/post/141840449415)] but I'm not a coder so I assume y'all will need to wait for the update yourselves. hopefully this clarifies some stuff though!

The bug itself is still happening after the update, but tagviewer _is_ able to view some tags so it's not completely broken?

**Comment by harrie5** [comment] 2016-03-28 17:15
I'm also not 100% certain about this, but I _think_ it could be working again on posts by people who've received the update? It seems to be working fine when I search for my posts, but it doesn't always work on other people's posts.

**Comment by nightpool** [comment] 2016-03-28 17:22
@harrie5 Hmm the problem we are seeing with notes is limited to posts with 1k+ notes made within the last month. do you have post like this you can test for us?

**Comment by harrie5** [comment] 2016-03-28 17:27
@nightpool ah yeah I just tested on this post [[http://captainharrie.tumblr.com/post/141447802900](http://captainharrie.tumblr.com/post/141447802900)] from a week ago, and it does stop loading after a while. I didn't notice initially since it loads pretty far, but it does stop eventually and I do know there were more tags.

**Comment by kingfisher-fire** [comment] 2016-03-29 05:34
For what it's worth, I have two posts that are 2000+ notes that are both about a year old which have abruptly lost their old notes as well. [This one](http://loquaciousquark.tumblr.com/post/116884562187/her-legs-arent-quite-as-long-as-his-but-they) is only loading about fifty notes for me, and [this one](http://loquaciousquark.tumblr.com/post/98849320342/not-ready-to-let-go-yet-inspired-by-x) is only loading about two hundred. So it's not just posts made within the last month that aren't working, unfortunately. (And for the record, I have not received the new notes/reply update yet, so I have no idea if that will affect it at all.)

**Comment by piearty** [comment] 2016-03-29 20:54
I appear to have gotten the new update but I still can't see more than like 100 notes for my 2k+ notes post, and only like 10 tags. No replies are appearing either.

**Comment by nightpool** [comment] 2016-03-29 21:03
@piearty can you link me the post? either here or in gitter (https://gitter.com/new-xkit/support)

**Comment by piearty** [comment] 2016-03-29 21:19
The post is [here](https://www.tumblr.com/dashboard/2/123853544388).

**Comment by nightpool** [comment] 2016-03-29 21:36
Which blog?

**Comment by piearty** [comment] 2016-03-29 22:17
[oops....](http://randumbdaze.tumblr.com/post/123853544387/i-got-bored-and-then-spent-19-hours-on-this-oops)

**Comment by nightpool** [comment] 2016-03-29 22:35
So far I've loaded about 900 notes on that post my manually scrolling through the notes popup, and about 127 tagged posts through TagViewer. This is on https://www.tumblr.com/dashboard/blog/randumbdaze/123853544387

Can you try there and tell me what you see?

**Comment by piearty** [comment] 2016-03-29 23:21
I just tried it right now. Definitely more loaded than before. Before there were only about 20 tags. I'm not sure why it changed.

**Comment by kingfisher-fire** [comment] 2016-03-29 23:26
As a quick update to my previous post now that I've gotten my new replies/notes, the first post I linked is still loading only about fifty notes for me, but the second post I linked is now loading multiple hundreds, with their associated tags, to the point that I gave up seeing how many would load. (Just in case that helps!)

**Comment by Meektepp** [comment] 2016-05-07 00:16
Dropping by to comment that I am experiencing erratic results with ReplyViewer and TagViewer, starting about two weeks ago.

Sometimes I see just a few of the replies and tags. Sometimes I get the message "There are no replies to this post," then later a few of the replies will be displayed. When TagViewer and ReplyViewer work as expected, a friend reports 150 is the max; she's taken many screenshots. Prior to whatever the heck Tumblr did in late March, it was possible to view 1,000 tags/replies through TagViewer and ReplyViewer. 

When I go to a post URL, notes/tags/replies are cut off; clicking on "more notes" no longer gives me everything. Sometimes I get 150 notes, sometimes just 50.

Unfortunately I cannot detect a pattern because of the sporadic results. It is hard to recreate. 

I'm hoping there may be a way to view 1,000 notes/tags/replies again.

**Comment by piearty** [comment] 2016-05-17 11:10
Update that this post http://randumbdaze.tumblr.com/post/128289780167/i-just-realized with 5k notes has currently 20 tags in tag viewer and 4 replies in reply viewer. Several tags which I knew were present before are now gone.

**Comment by piearty** [comment] 2016-06-09 14:52
Update again. This is happening with posts of mine that have around 170 notes.

**Comment by thebase16** [comment] 2016-06-12 18:24
This is happening on a post of mine with around 3.5k notes. Tag veiwer will only load ~40 tags or so whenever I check. It appears to be loading only the most recent tags

**Comment by nightpool** [comment] 2016-09-28 13:03
closing because this only affects a small subset of posts now

**Closed by nightpool** 2016-09-28 13:03 UTC
Labels: E-ReplyViewer, E-TagViewer, Tumblr's Fault
