### ISSUE TITLE
I post a "Read more" on firefox it won't show it

### ISSUE THREAD

**Issue by selloutoftheshield** [new-xkit/XKit#512] opened 2015-09-18 15:54 UTC
![capture](https://cloud.githubusercontent.com/assets/14349960/9964011/002e3448-5dfc-11e5-8afe-591683cf22ae.PNG)
That's what the "Read more" looks like

**Comment by blackjackkent** [comment] 2015-09-19 01:00
Closing as dupe of #507

**Closed by blackjackkent** 2015-09-19 01:00 UTC
