### ISSUE TITLE
Reblog Display Options doubles up in sidebars

### ISSUE THREAD

**Issue by 00Davo** [new-xkit/XKit#670] opened 2015-10-25 06:52 UTC
I suspect most XKit users already replaced the blog sidebar with Open In Tabs anyway, but yeah anyway: if you're running the nested style with Reblog Display Options, then in blog sidebars you get *both* the nested and flat reblogs on each post. Looks like this:

![screen shot 2015-10-25 at 5 51 06 pm](https://cloud.githubusercontent.com/assets/610876/10714362/015ec50a-7b41-11e5-9182-8a6929e86a77.png)

I assume the flat style isn't properly hidden when contained in the sidebar, or something along those lines. Might be worth addressing?

**Comment by ThePsionic** [comment] 2015-10-25 09:42
Duplicate of #671

**Closed by ThePsionic** 2015-10-25 09:42 UTC
