### ISSUE TITLE
Remove XKit Packs

### ISSUE THREAD

**Issue by 0xazure** [new-xkit/XKit#484] opened 2015-09-10 15:06 UTC
Immediately after release, XKit Packs were disabled.
> [So, less than 12 hours after it’s release, I am temporarily disabling creating/editing XKit Packs](http://xkit-extension.tumblr.com/post/86585386917/xkit-packs-part-ii)

This is effectively dead code that should be removed from the codebase.

Announcement links:
- http://xkit-extension.tumblr.com/post/86541896872/1-xkit-packs-historically-developing-for-xkit
- http://xkit-extension.tumblr.com/post/86585386917/xkit-packs-part-ii

Wiki links:
- https://github.com/new-xkit/XKit/wiki/XKit-Packs

Related: #178.

**Comment by nightpool** [comment] 2015-09-10 15:16
80% sure this is a dupe of another issue... let me check

**Comment by Wolvan** [comment] 2015-09-10 15:31
If we remove packs, we have to remove code in both ``xkit_patches`` and ``xkit_updates``

**Comment by blackjackkent** [comment] 2015-09-10 16:31
Started poking at this; seems pretty straightforward (assuming this is in fact already completely unused). Need to do further testing though.

**Closed** 2015-09-10 20:50 UTC
Labels: enhancement, needs review
