### ISSUE TITLE
Glowing Follow doesn't work properly

### ISSUE THREAD

**Issue by xThreeh** [new-xkit/XKit#844] opened 2015-12-06 13:27 UTC
Hi guys, i was reviewing this extension and some blogs not glow button. 
why is this happening? could be much brighter this button in some blogs you can not see very well or at least choose the color we want to glow.

![screenshot_51](https://cloud.githubusercontent.com/assets/16139465/11613550/c5644ff0-9c03-11e5-9b2d-d6f9bdfba23c.png)
![screenshot_52](https://cloud.githubusercontent.com/assets/16139465/11613552/cb83e4f4-9c03-11e5-846f-bd188784666e.png)

PS: Excuse my English, I speak Spanish but I try to help.

**Comment by Wolvan** [comment] 2015-12-06 14:52
Glowing follow? Where did you find that setting?

**Comment by ThePsionic** [comment] 2015-12-06 15:14
Glowing Follow, as in the extension.

**Comment by Wolvan** [comment] 2015-12-06 15:15
I completely forgot we had this. Gotta look into that

**Comment by xThreeh** [comment] 2015-12-23 06:35
@Wolvan up

**Comment by nightpool** [comment] 2015-12-23 20:06
This is a dupe of the other blog controls issue.

**Comment by Wolvan** [comment] 2015-12-23 20:15
@nightpool it is not.

**Comment by nightpool** [comment] 2015-12-23 20:54
Okay, my bad. Mind updating with a better description? I can't make heads
or tails of what the broken or expected behavior is in this bug report.

(Remember, we can edit other people's issues for a reason!)

**Comment by nightpool** [comment] 2015-12-24 00:45
@Wolvan from the fix, it was a dupe fwiw

**Comment by nightpool** [comment] 2015-12-24 00:45
we should have updated that issue and close this one

**Comment by Wolvan** [comment] 2015-12-24 00:46
I thought it was the in-dashboard follow buttons that should glow though, not the blog buttons

**Closed** 2015-12-24 00:47 UTC
Labels: E-Glowing Follow
