### ISSUE TITLE
Wrap tags on in-dashboard blog panel

### ISSUE THREAD

**Issue by noahleigh** [new-xkit/XKit#408] opened 2015-09-02 00:49 UTC
With the "wrap tags" tweak enabled, it doesn't wrap tags in the sidebar-blog-view, and those tags are unscrollable because the tweak disables that.

**Comment by nightpool** [comment] 2015-09-02 01:00
this is a duplicate of https://github.com/new-xkit/XKit/issues/194

only happens to some users, and inconsistently at that.

**Comment by noahleigh** [comment] 2015-09-02 01:28
Thanks, I've subscribed to that issue now.

**Comment by nightpool** [comment] 2015-09-02 02:20
reopening this because further investigation reveals this is a separate issue.

**Comment by noahleigh** [comment] 2015-09-02 02:22
Details?

**Comment by nightpool** [comment] 2015-09-02 02:26
Looking into it now, but this seems to be tag wrapping specific—unlike the issue I liked to which was a global issue with all of the blog sidebar and xkit extensions

**Closed** 2016-01-31 03:00 UTC
Labels: needs review
