### ISSUE TITLE
Reblog Display Options deletes answers to ask.

### ISSUE THREAD

**Issue by gloomykid** [new-xkit/XKit#644] opened 2015-10-17 00:55 UTC
flat lay out:
![ss 2015-10-17 at 02 54 11](https://cloud.githubusercontent.com/assets/13604430/10556058/6e19f340-747a-11e5-9e2b-491f23039152.png)

nested lay out:
![ss 2015-10-17 at 02 54 23](https://cloud.githubusercontent.com/assets/13604430/10556061/75b8edea-747a-11e5-9047-7a887f30ec0a.png)

**Comment by nightpool** [comment] 2015-10-24 18:54
@hobinjk you were able to reproduce? If you could put an example post here that would be great.

**Comment by hobinjk** [comment] 2015-10-24 19:02
@nightpool  http://120983019283-testing.tumblr.com/post/131826469124/teen-stanley-b3-and-stanford-c3-hugging-if

**Comment by nightpool** [comment] 2015-10-24 19:06
Can't reproduce on my account, hmmm...

do you want to take a shot at debugging this?

**Comment by nightpool** [comment] 2015-10-25 18:37
fixed in #674

**Closed** 2015-10-26 03:04 UTC
Labels: bug, E-Reblog Display Options
