### ISSUE TITLE
Tracked Tags: Also show in other pages not just "Posts"

### ISSUE THREAD

**Issue by pepoluan** [new-xkit/XKit#935] opened 2016-01-30 15:51 UTC
Currently, the "Tracked Tags" sidebar/sidepanel appears only while I'm in the "Posts" page, or in the Dashboard, or in the /tagged/ page.

I often spend my time back and forth between the "Activities" page and the tags, but there is no "Tracked Tags" sidepanel in the "Activities" page, so it's a bit annoying to either (1) click on the address bar and type "tag" (to invoke the browser's historical list) or (2) go to "Posts" first, wait for the "Tracked Tags" sidepanel to appear, then go to the tag I want to view.

I suggest modifying the "**Tag Tracking+**" extension to show the "Tracked Tags" sidepanel in other pages, too. Maybe as a list of checkboxes, enabling people to choose where they want the sidepanels to appear.

**Comment by Wolvan** [comment] 2016-01-31 16:56
See #811, @nightpool still hasn't gotten back to me about that PR

**Comment by nightpool** [comment] 2016-01-31 18:35
@wolvan the PR hasn't changed since my review. We need a more specific
check then is_tumblr_page.

**Comment by nightpool** [comment] 2016-01-31 18:36
closed as dupe of #810

**Closed by nightpool** 2016-01-31 18:36 UTC

**Comment by Wolvan** [comment] 2016-01-31 18:37
I am still asking why. It works and has not broken anything? Why make super complicated checks
