### ISSUE TITLE
One Click Reply can't identify usernames properly

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#82] opened 2015-08-01 05:26 UTC
From the askbox:

this just started happening today. im on chrome & my version of one click reply is 2.0.4. when someone replies who doesnt have any hyphens in their url, it shows up as "undefined" in the reply, even if i have the "show icon thing" turned on in settings for it. their icon will show up in the post but instead of their url being there, it will still say undefined. when someone replies who has a hyphen in their url, their url shows up just fine & it works.

**Comment by agrunwald82** [comment] 2015-08-01 09:27
additionally, at least once (2/3 times) it happened with me that the text of their reply was also, simply, "undefined", erasing their actual reply

**Comment by fonbella** [comment] 2015-08-01 21:31
I'm using Chrome version 44.0.2403.125 and I am having the same issue with one click reply changing people's urls simply to "undefined". Additionally, and this has been happening for a longer time, even though I have the option to post a tag with the person's url when replying to someone, this doesn't work. The tag field is simply empty and I need to enter the url manually.

**Comment by nightpool** [comment] 2015-08-01 21:35
intuitively, this is probably related to #76 also—I'm trying to find all of
the places that were affected by this tumblr api change and I'll make sure
to look through here

**Comment by nightpool** [comment] 2015-08-07 16:21
(Wasn't related to #76, just to be clear.)

**Comment by blackjackkent** [comment] 2015-08-07 16:45
Dupe of #158 though?

**Comment by nightpool** [comment] 2015-08-07 16:58
@blackjackkent most people would probably say #158 was a dupe of this, seeing as it was reported first, but as you're working on the issue I'm fine closing whichever.

**Comment by blackjackkent** [comment] 2015-08-07 17:29
Haha whoops. Either works. :+1:

**Comment by nightpool** [comment] 2015-08-07 17:42
to summarize, things that should work, but seem not to:

 - replying from the real-time notes popup in the bottom right corner of the screen
 - replying to people without hyphens in their usernames. (maybe?)

@blackjackkent to fix.

**Comment by rosalindwills** [comment] 2015-08-07 17:51
Per @agrunwald82 's comment I think the hyphen thing is a red herring.

**Comment by blackjackkent** [comment] 2015-08-07 17:51
Per @agrunwald82 's comment I think the hyphen thing is a red herring.

**Comment by bvtsang** [comment] 2015-08-08 03:11
Closed via #167.

**Closed by bvtsang** 2015-08-08 03:11 UTC
Labels: bug, claimed, E-One-Click Reply
