### ISSUE TITLE
Left most buttons are not showing up in button-container on blogs

### ISSUE THREAD

**Issue by version365** [new-xkit/XKit#1037] opened 2016-05-01 07:18 UTC
Left most buttons on the button-container (i.e. _Message_ & _View_ on others' blog, _Edit_ & _gotodash_ on my blog) are not showing up..
http://i.imgur.com/k4SoOVN.png
http://i.imgur.com/TBDUrXq.png
http://i.imgur.com/VjD6BxQ.png

How to fix this?

**Comment by nightpool** [comment] 2016-05-01 18:35
Dupe of [#1014 On-Blog icons are semi-broken](https://github.com/new-xkit/XKit/issues/1014)

**Closed by nightpool** 2016-05-01 18:35 UTC
