### ISSUE TITLE
Deleting drafts with Drafts+ and Mass Deleter doesn't work

### ISSUE THREAD

**Issue by realityfabric** [new-xkit/XKit#1016] opened 2016-04-12 16:33 UTC
I'm using Chromium version 49.0.2623.108 Ubuntu 15.10, and using Drafts+ to try to delete a single post in the Mass Editor from Drafts+ fails, as well as using the Delete 100 and Delete 1000 posts buttons.

With the Delete 100 and Delete 1000 posts buttons it was able to find all of the drafts and their IDs, it showed the proper number of drafts, but it failed to delete any drafts.

**Comment by Namicchi** [comment] 2016-04-30 17:46
I second this. Delete 100 and Delete 1000 doesn't work even when I switch off all extensions in the Chrome, anti-virus program and Windows Defense.

**Comment by nightpool** [comment] 2016-04-30 21:35
dupe of #620

**Closed by nightpool** 2016-04-30 21:35 UTC
