### ISSUE TITLE
Tag Tracking+ can't reset its counts with the tagged page redesign

### ISSUE THREAD

**Issue by Fujiko-chan** [new-xkit/XKit#1953] opened 2020-08-07 20:56 UTC
I'm not sure if it's just me, but my Tag Tracking+ extension is not working properly. Even if i check the tag, the [new] indicator doesn't disappear. And because of tumblr's soft refresh, xkit's icon disappears when I go back to my dash after checking said tag.

Also, does the page /tagged/[tag] behave differently on different browsers? I can still choose between the grid layout and the list layout on chrome but not on firefox.

Is it just me? Thank you in advance!

**Comment by AprilSylph** [comment] 2020-08-07 21:01
It's not just you - Tag Tracking+ can't reset its counts if you have the tagged page redesign. We're aware of this issue and are waiting to get the redesign ourselves so that we can look at possible solutions.

**Comment by Fujiko-chan** [comment] 2020-08-07 21:29
> It's not just you - Tag Tracking+ can't reset its counts if you have the tagged page redesign. We're aware of this issue and are waiting to get the redesign ourselves so that we can look at possible solutions.

Oh, I see! Thank you so much!

**Comment by lihatt** [comment] 2020-08-10 20:43
> Also, does the page /tagged/[tag] behave differently on different browsers? I can still choose between the grid layout and the list layout on chrome but not on firefox.

Lucky you! I'm forced to grid no matter what. Are you possibly logged in as a different user (or not logged in at all) on Chrome?

**Comment by Fujiko-chan** [comment] 2020-08-11 17:38
> Lucky you! I'm forced to grid no matter what. Are you possibly logged in as a different user (or not logged in at all) on Chrome?

Yep, logged in as a different user!

**Comment by lihatt** [comment] 2020-08-12 03:19
I think that's most likely the cause, then, not the browser itself.

**Comment by lihatt** [comment] 2020-12-04 07:23
Count resetting was working for a while but the tracked tag page has changed somewhat again, and appears to have broken count resetting once more. This is what I currently have:

![Untitled-1](https://user-images.githubusercontent.com/68124115/101133609-e7dc5600-35bd-11eb-9df5-e949b70d1618.jpg)

The bits in red are new since I last looked on November 27th. (Actually I had some version of the "offset grid / list" option at the top right of the posts before, but the buttons looked different.) And the URL now has a **?sort=recent** or **?sort=top** argument in it which I'm pretty sure is new.

**Comment by AprilSylph** [comment] 2021-02-11 23:15
resolved by #2036

**Closed by AprilSylph** 2021-02-11 23:15 UTC

**Comment by lihatt** [comment] 2021-03-13 22:55
This is a weird long shot, but is there any possibility an apostrophe in a tag could be interfering with counting or (somehow) the entire extension's function? I follow one tag that has an apostrophe in it, and its count never seems to reset, plus when I load that tag page, the tracked tags are not inserted in the sidebar as I have it set up to do (which works on all my other tags).
