### ISSUE TITLE
this extension is automatically disabled in private mode on firefox

### ISSUE THREAD

**Issue by sundubu** [new-xkit/XKit#118] opened 2015-08-04 01:27 UTC
when i tried to look up how to turn extensions back on in private mode, firefox support was saying that they tell extensions whether youre in private mode, and the extension itself decides whether or not it will still run when users are using private windows. would really appreciate an option to leave it on when im browsing on private! thanks.

**Comment by 0xazure** [comment] 2015-08-13 00:34
Closing as a dupe of #207.

**Closed by 0xazure** 2015-08-13 00:34 UTC
Labels: B-Firefox
