### ISSUE TITLE
Tracked tags are messed up.

### ISSUE THREAD

**Issue by AuraSweet** [new-xkit/XKit#687] opened 2015-10-29 21:36 UTC
They no longer show notifications, and it takes you straight to select when you click on the tags instead of the actual tags.
![tumblr issues2](https://cloud.githubusercontent.com/assets/14351360/10832728/ae5940fa-7e52-11e5-9d55-2e6aa76897db.png)
![tumblr issues3](https://cloud.githubusercontent.com/assets/14351360/10832745/cc6bff92-7e52-11e5-8118-3ea6a14e1d2f.png)

**Comment by Wolvan** [comment] 2015-10-29 21:39
Duplicate of #686

**Closed by Wolvan** 2015-10-29 21:39 UTC
