### ISSUE TITLE
Mass Unlike: Number of likes doesn't update

### ISSUE THREAD

**Issue by hobinjk** [new-xkit/XKit#48] opened 2015-07-30 05:53 UTC
After mass unliking the number of likes seems to stay the same. This may just be that Mass Unlike fails as doesn't notify people that it failed.

**Comment by WyohKnott** [comment] 2015-08-06 13:43
I can't reproduce on Firefox.

**Comment by ThePsionic** [comment] 2015-11-05 22:27
Tested this and works as expected. Closing.

**Closed by ThePsionic** 2015-11-05 22:27 UTC
Labels: unconfirmed
