### ISSUE TITLE
Post will sometimes double what you're replying to

### ISSUE THREAD

**Issue by anakhasilver** [new-xkit/XKit#162] opened 2015-08-07 13:30 UTC
I'm not seeing this specifically, just a version with drafts. However, I've experienced this (as well as my fiancee) WITHOUT drafting where occasionally, it'll be fine before we post, but then doubled the original afterward.
Example:

User1:
I want to share this thing
User1:
I want to share this thing
User 2:
This thing is cool

You can immediately go back in and edit out the doubled comment, but it's baffling that this is happening. My guess is something with Editable Reblogs?

Using Windows 7 and latest Chrome as well as latest Xkit.

**Comment by ThePsionic** [comment] 2015-08-07 13:56
Related to #100

**Comment by nightpool** [comment] 2015-08-07 15:51
definitely a dupe of #100.

**Closed by nightpool** 2015-08-07 15:51 UTC
