### ISSUE TITLE
XKit disappearing and reappearing from dashboard

### ISSUE THREAD

**Issue by hotpotofawsomeness** [new-xkit/XKit#1952] opened 2020-08-07 20:44 UTC
Most, if not all functions have now returned since tumblr made the new dashboard (THANK YOU!!). 
However, xkit regularly disappears along with all its features. Some times refreshing tumblr is enough to get it back, other times just got to wait tumblr out.

**Comment by AprilSylph** [comment] 2020-08-07 20:46
duplicate of #1869

**Closed by AprilSylph** 2020-08-07 20:46 UTC
