### ISSUE TITLE
Editable Reblogs mess up queue/scheduling

### ISSUE THREAD

**Issue by maswartz** [new-xkit/XKit#804] opened 2015-11-28 18:44 UTC
Since about Wednesday 11/25/15 ish Editable Reblogs have been causing queues and scheduled posts to default to their default times no matter what setup you have in place. In other words when you schedule a post it'll be scheduled for tuesday at 10 AM no matter what time is entered. And queued posts will be queued out of order for the setting you have. I have one of my side blogs set to post 4 a day so the times are like 2:35 5:15 etc but I just queued one and it was set for last Wednesday at 3:00

**Comment by bvtsang** [comment] 2015-12-03 17:56
I'm still [unable to reproduce](http://files.catbox.moe/2964fb.mp4) this issue. With Editable Reblogs 3.0.4, I can set arbitrary scheduled times just fine.

Which specific steps did you take to produce this issue?

**Comment by maswartz** [comment] 2015-12-03 17:59
Since our chat a few days ago it hasn't happened since. So I can only assume I hit the button before putting in a time.

**Comment by blackjackkent** [comment] 2015-12-04 00:59
Closing since it seems like this isn't reproducible.

**Closed by blackjackkent** 2015-12-04 00:59 UTC
