### ISSUE TITLE
Queued posts don't retain caption

### ISSUE THREAD

**Issue by dlmarquis** [new-xkit/XKit#123] opened 2015-08-04 06:48 UTC
Full text of issue:

Maybe it’s tumblr being stupid or, a chrome issue, or maybe the new-xkit-extension is having issues, but I’m finding a lot of the stuff that comes out of my queue posts without the caption/full blog post. It’s definitely there when I initially put the post in my queue, but when it’s finally up it’s just the title or the video in question and nothing else. I swear I’m not purposely removing the content!

**Comment by nightpool** [comment] 2015-08-04 16:38
Are the captions there when the posts are in your queue? (I.e. After you
save them but before they get published automatically)

**Comment by ThePsionic** [comment] 2015-08-04 21:43
I use Chrome and I cannot reproduce this issue; all my queued posts have been spitting out just fine.

**Comment by dlmarquis** [comment] 2015-08-05 18:51
This was an issue pulled from a blog mention, and I can't reproduce it either. I'll try to contact the original asker for more info. Otherwise, I'll close the issue.

**Comment by dlmarquis** [comment] 2015-08-05 20:25
We had a suggestion that this was caused by Lethe.

@hobinjk, you'd know best whether this makes sense or not.

**Comment by dlmarquis** [comment] 2015-08-05 20:29
More info from a Firefox user (who later fixed the problem by restarting Firefox):

Almost all of the comics, pictures, and videos I’ve reblogged today - so not many yet, thankfully - actually had some kind of caption and/or commentary beneath them, but it vanished as soon as I hit “Post”.

I just installed the new xkit this morning and enabled the Editable Reblogs, so I believe that might have caused the problems. I’ve already sent an ask to the new xkit and hope they’ll be able to help me out (even in only confirming that there isn’t a problem on their end) so please bear with me and my excited tags that don’t make any sense now because the commentary above them isn’t there anymore.

**Comment by ThePsionic** [comment] 2015-11-06 15:32
Was allegedly fixed in #169.

**Closed by ThePsionic** 2015-11-06 15:32 UTC
Labels: unconfirmed
