### ISSUE TITLE
Enhanced Queue doesn't work

### ISSUE THREAD

**Issue by hyleore** [new-xkit/XKit#1799] opened 2020-04-16 16:59 UTC
Hello!

Enhanced queue doesn't change anything on my queue page. I don't see the shuffle queue button anywhere even though that's why I needed that extension. I'm using Firefox.

**Comment by AprilSylph** [comment] 2020-04-16 17:01
Enhanced Queue is one of the many extensions that has not yet been updated for the new Tumblr dashboard. If you revert back to the old dashboard in your dashboard settings, it will work. Please read our post about the new dashboard here: https://new-xkit-extension.tumblr.com/post/613164737228832768/

closing as duplicate of #1770

**Closed by AprilSylph** 2020-04-16 17:01 UTC
